### ISSUE TITLE
Feed disappears when site changes to SSL

### ISSUE THREAD

**Issue by bootsy123** [cogdog/feed2js#10]
Hello,

Wonderful script! However I noticed today the RSS feed was gone from my site and at first I thought it was because of a server connection at the .org site but then I installed the script on my server and got the same thing. I accessed the site on a different computer and the RSS feed was in place. But on the machine I was working on I noticed my ecommerce site had switched to SSL because I was navigating around the cart (the RSS is in the footer on all pages).  When on the SSL pages, the RSS feed was gone. When I switched to the site URL without SSL the feed returned. 

Any way to get this to work on both?

I have the script hosted on one of my other accounts.

**Comment by bateller** [comment]
Sorry for the delay in responding to this issue. It has been resolved for some time. SSL support was added.
