### ISSUE TITLE
Access to close Issues

### ISSUE THREAD

**Issue by bateller** [cogdog/feed2js#15]
Alan,
 Can you give me access to close issues and push commits to this repository so I can update Magpie?

Thanks,
Brian

**Comment by axelseaa** [comment]
Alan: Feel free to add me also if you want some additional backup - we still actively use feed2js also

**Comment by bateller** [comment]
@axelseaa Hey Aaron hows it going? I'm looking to do some updates to feed2js. Do you think you would you be able to provide some assistance?

**Comment by cogdog** [comment]
Wow, this is almost a dream come true. Gave you both commit access that should also let you address issues. I have given this zero attention for 2 years.

**Comment by axelseaa** [comment]
@bateller absolutely
