### ISSUE TITLE
PHP 8 incompatibility

### ISSUE THREAD

**Issue by PaddyWhacks** [cogdog/feed2js#29]
Anyone else struggling to run feed2js on PHP 8? Works fine on PHP 7.4 for me, but after tupdating new RSS items aren't pulling through.

**Comment by cogdog** [comment]
I'm surprised it works at all anymore! Since the code relies on the ancient [Magpie Parser](https://github.com/kellan/magpierss/) which I cannot debug, I can't be of any help.

**Comment by PaddyWhacks** [comment]
Haha yeah the code is ancient!
