### ISSUE TITLE
Websites validate, but are not working

### ISSUE THREAD

**Issue by wimplo79** [cogdog/feed2js#33]
Hello, I can get the website to validate.  However, once it throws in the code for backslashes and what not, the sites immediately invalidate on feed2js.  I can go to them in a browser and view all the data, but it appears something in the coding that it is generated for the feed is invalidating the website url.

**Comment by cogdog** [comment]
Apologies, Feed2JS relies on a very very old RSS parser and the message about "invalid" which in the day was the usual case now ends up as default error when the parser fails to read the data. I can't really fix it.

The thing that seems to usually work is to "rinse" the source feed through [Feedburner](https://feedburner.google.com/) and use the proxy feed it creates in Feed2JS.
