### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by ninjaPowow** [cogdog/feed2js#34]
Hello, my feed used to work perfectly fine until maybe a month ago, but now all feeds seem to fail. Even the example http://cogdogblog.com/feed/ doesn't work. If I use the validator test that the error links to, they all still validate.
What could it be? Is the project still being worked on?

**Comment by cogdog** [comment]
Sorry but there's not much I can do any more, the RSS Parser is extremely old. In the past the message about being an invalid feed was accurate for when the parser threw an error, but now very few feeds work (including my own blog).

 The only work around I have found that still works is to pass feeds through [Feedburner](https://feedburner.google.com). I will make this more clear, but this is after all, almost 20 years old!
